# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: ubuntu-20.04

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
- script: |
    sudo apt-get install awscli -y
    aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID) --profile qas-maqplan && aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY) --profile qas-maqplan
  displayName: 'AWS Configure'
  
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: Cache@2
  inputs:
    key: '"yarn" | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
       yarn | "$(Agent.OS)"
       yarn
    path: $(YARN_CACHE_FOLDER)
  displayName: 'Cache Yarn packages'

- script: yarn --frozen-lockfile
  displayName: 'Install Project'

- script: yarn build
  displayName: 'Generate bundle'

- script: yarn deploy-siscor-qas
  displayName: 'Deploy to AWS'
  env:
    AWS_REGION: 'us-east-1'
